### ISSUE TITLE
Update tooltip and doc

### ISSUE THREAD

**Issue by fizerkhan** [segment-integrations/analytics.js-integration-atatus#4]
For an advanced option **Enable Source Map**,  Segment has description in doc and Tooltip in integration page as **Enable loading of source map for atatus.js. Useful for debugging**

But it is incorrect. Because it is not intended to source map for atatus.js. It is a sourcemap for our user site's minified script. So description and tooltip should be

```
Enable source maps to translate the minified code references back into the original source in the error stack trace.
```

**Comment by ndhoule** [comment]
Hey @fizerkhan, this description is similar to the description given in your PR in that it's unclear how a user is supposed to use this in practice. Please link us to relevant Atatus documentation or describe in detail exactly how a user ends up using this in practice.

We also need to rename this; **Enable Source Map** does not tell a user enough about what this option does.

**Comment by fizerkhan** [comment]
@ndhoule Yes, the description is same as in pull request. I can see that you have updated the description in tooltip, but not in the integration docs. Can you please update the same in docs too?

You can refer Atatus doc of [how to use sourcemap](https://www.atatus.com/docs/sourcemaps)

**Comment by hankim813** [comment]
docs have been updated
